title: "Талько Елена Вадимовна"
email: talko.denis.andreevich@gmail.com
description: >-
  It's resume for my mother.
baseurl: "/resume" 
url: "https://talkoelenavadimovna.github.io"
github_username: TalkoDenis